// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Light Transport Entertainment Inc.
#include "usd-validation.hh"
#include <sstream>
namespace lightusd {
namespace next {

namespace {

std::string Pluralize(size_t n, const char *noun) {
  std::ostringstream ss;
  ss << n << " " << noun;
  if (n != 1) {
    ss << "s";
  }
  return ss.str();
}

}  // namespace


const ValidationRuleInfo* GetValidationRuleTable(size_t* count) {
  // Ordered by (group, id). `vol.*` rules run under the geom group (Volume is
  // a renderable; see the Volume dispatch note). Package/crate/checker rules
  // are emitted by the byte-container checks in lusdchecker, which shares
  // this registry.
  static constexpr ValidationRuleInfo kRules[] = {
      {"arkit.layer.extension", "arkit",
       "subLayer assets must be usd/usda/usdc/usdz layers"},
      {"arkit.material.binding", "arkit",
       "material bindings must resolve to an existing Material prim"},
      {"arkit.normalMap.scaleBias", "arkit",
       "8-bit normal maps must author scale (2,2,2,1), bias (-1,-1,-1,0), and sourceColorSpace raw"},
      {"arkit.package.fileExtension", "arkit",
       "a package may only contain USD layers and exr/jpg/jpeg/png textures"},
      {"arkit.package.rootLayer", "arkit",
       "the package root layer must be a .usdc crate layer"},
      {"arkit.prim.type", "arkit",
       "prim types must be in the ARKit-supported whitelist"},
      {"arkit.shader.connection", "arkit",
       "at most one connection source per shader input"},
      {"arkit.shader.id", "arkit",
       "shaders must use id-source UsdPreview/MaterialX node ids"},
      {"arkit.shader.implementationSource", "arkit",
       "shaders must use the `id` implementation source"},
      {"arkit.stage.defaultPrim", "arkit",
       "the stage must author a defaultPrim"},
      {"arkit.stage.metersPerUnit", "arkit",
       "the stage must author metersPerUnit"},
      {"arkit.stage.upAxis", "arkit",
       "the stage must author upAxis = \"Y\""},
      {"arkit.texture.format", "arkit",
       "textures must be exr/jpg/jpeg/png"},
      {"checker.coverage.skipped", "checker",
       "a requested validation group was inapplicable to the input (--require-all-groups)"},
      {"core.apiSchema.duplicate", "core",
       "an API schema must not be applied twice with the same instance name"},
      {"core.apiSchema.instance", "core",
       "multiple-apply API schemas require an instance name; single-apply forbid one"},
      {"core.apiSchema.name", "core",
       "apiSchemas entries must be valid identifiers"},
      {"core.apiSchema.unknown", "core",
       "apiSchemas entries should name a known API schema"},
      {"core.attr.allowedTokens", "core",
       "a token attribute value must be one of its allowedTokens"},
      {"core.attr.colorSpace", "core",
       "attribute colorSpace must reference a defined color space"},
      {"core.attr.connectability", "core",
       "connectability metadata must be `full` or `interfaceOnly`"},
      {"core.attr.customData", "core",
       "attribute customData must be a dictionary"},
      {"core.attr.elementSize", "core",
       "primvar elementSize must be a positive integer"},
      {"core.attr.interpolation", "core",
       "interpolation metadata must be a valid interpolation token"},
      {"core.attr.outputName", "core",
       "outputName metadata must be a valid identifier"},
      {"core.attr.renderType", "core",
       "renderType metadata must be a string"},
      {"core.attr.sdrMetadata", "core",
       "sdrMetadata must be a dictionary"},
      {"core.attr.timeSamples", "core",
       "timeSamples must have finite, ordered times and consistent value types"},
      {"core.attr.unauthoredValuesIndex", "core",
       "unauthoredValuesIndex must be a valid index"},
      {"core.clips", "core",
       "the clips dictionary must be well-formed"},
      {"core.clips.active", "core",
       "clips active entries must be (time, assetIndex) pairs into assets"},
      {"core.clips.assets", "core",
       "clips assets must be non-empty asset paths"},
      {"core.clips.primPath", "core",
       "clips primPath must be an absolute prim path"},
      {"core.clips.template", "core",
       "template clips metadata must be complete and consistent"},
      {"core.clips.times", "core",
       "clips times entries must be (stageTime, clipTime) pairs"},
      {"core.composition.attributeTypeMismatch", "core",
       "an attribute must have one declared type across composition arcs"},
      {"core.composition.error", "core",
       "the stage must compose without composition errors (--composed)"},
      {"core.composition.inherits", "core",
       "inherits arcs must target valid absolute prim paths"},
      {"core.composition.over", "core",
       "an over must have a defining specifier somewhere in composition"},
      {"core.composition.payload", "core",
       "payload arcs must have valid asset paths and prim targets"},
      {"core.composition.propertyKindMismatch", "core",
       "a property must not be both an attribute and a relationship across arcs"},
      {"core.composition.reference", "core",
       "reference arcs must have valid asset paths and prim targets"},
      {"core.composition.specializes", "core",
       "specializes arcs must target valid absolute prim paths"},
      {"core.composition.variantSelection", "core",
       "variant selections must name an existing variant"},
      {"core.composition.variantSet", "core",
       "variantSets metadata must be well-formed"},
      {"core.schema.attributeType", "core",
       "attribute is declared with a different type than its schema defines"},
      {"core.dependency.unresolvable", "core",
       "authored asset dependencies must be resolvable (usdchecker MissingReferenceValidator)"},
      {"core.layer.colorConfiguration", "core",
       "colorConfiguration must be a non-empty asset path"},
      {"core.layer.colorManagementSystem", "core",
       "colorManagementSystem must be a non-empty token"},
      {"core.layer.customLayerData", "core",
       "customLayerData must be a dictionary"},
      {"core.layer.defaultPrim", "core",
       "an authored defaultPrim must name a root prim"},
      {"core.layer.defaultPrim.missing", "core",
       "a referenceable asset should author a defaultPrim (usdchecker asset check)"},
      {"core.layer.expressionVariables", "core",
       "expressionVariables must be a dictionary"},
      {"core.layer.framesPerSecond", "core",
       "framesPerSecond must be a positive finite number"},
      {"core.layer.kilogramsPerUnit", "core",
       "kilogramsPerUnit must be a positive finite number"},
      {"core.layer.layerRelocates.identity", "core",
       "a relocate must not map a path to itself"},
      {"core.layer.layerRelocates.source", "core",
       "relocate sources must be absolute prim paths"},
      {"core.layer.layerRelocates.target", "core",
       "relocate targets must be absolute prim paths or empty (delete)"},
      {"core.layer.metersPerUnit", "core",
       "metersPerUnit must be a positive finite number"},
      {"core.layer.owner", "core",
       "owner must be a non-empty string"},
      {"core.layer.subLayerOffset", "core",
       "subLayer offsets must be finite with non-zero scale"},
      {"core.layer.subLayers", "core",
       "subLayers entries must be non-empty asset paths"},
      {"core.layer.timeCodeRange", "core",
       "startTimeCode must not exceed endTimeCode"},
      {"core.layer.timeCodesPerSecond", "core",
       "timeCodesPerSecond must be a positive finite number"},
      {"core.layer.upAxis", "core",
       "an authored upAxis must be X, Y, or Z"},
      {"core.prim.assetInfo", "core",
       "assetInfo must be a dictionary"},
      {"core.prim.customData", "core",
       "prim customData must be a dictionary"},
      {"core.prim.instanceable", "core",
       "instanceable must be authored on a prim that can be instanced"},
      {"core.prim.kind", "core",
       "kind must be a known model kind and respect the model hierarchy"},
      {"core.prim.name", "core",
       "prim names must be valid USD identifiers"},
      {"core.relationship.bindMaterialAs", "core",
       "bindMaterialAs must be strongerThanDescendants or weakerThanDescendants"},
      {"core.relationship.customData", "core",
       "relationship customData must be a dictionary"},
      {"core.relationship.variability", "core",
       "relationships must be uniform (varying is not meaningful)"},
      {"core.schema.CollectionAPI.applied", "core",
       "collection properties require CollectionAPI to be applied"},
      {"core.schema.CollectionAPI.excludes", "core",
       "collection excludes must be valid paths inside the collection"},
      {"core.schema.CollectionAPI.expansionRule", "core",
       "expansionRule must be a valid expansion token"},
      {"core.schema.CollectionAPI.includeRoot", "core",
       "includeRoot must be a bool and consistent with includes"},
      {"core.schema.CollectionAPI.instance", "core",
       "CollectionAPI requires an instance name"},
      {"core.schema.CollectionAPI.property", "core",
       "collection properties must use the collection: namespace shape"},
      {"core.schema.CollectionAPI.relationship", "core",
       "collection includes/excludes must be relationships"},
      {"core.schema.ColorSpaceAPI.applied", "core",
       "colorSpace:name requires ColorSpaceAPI to be applied"},
      {"core.schema.ColorSpaceAPI.name", "core",
       "colorSpace:name must reference a defined color space"},
      {"core.schema.ColorSpaceDefinitionAPI.applied", "core",
       "color space definitions require ColorSpaceDefinitionAPI"},
      {"core.schema.ColorSpaceDefinitionAPI.coordinates", "core",
       "color space definition chromaticity coordinates must be finite"},
      {"core.schema.ColorSpaceDefinitionAPI.curve", "core",
       "color space transfer-curve parameters must be valid"},
      {"core.schema.ColorSpaceDefinitionAPI.name", "core",
       "a color space definition must author a name"},
      {"core.schema.singleApply.instance", "core",
       "single-apply API schemas must not carry an instance name"},
      {"core.xformOp.order", "core",
       "xformOpOrder entries must reference authored xformOp attributes"},
      {"crate.decode.warning", "crate",
       "the crate decoder reported a recoverable inconsistency"},
      {"crate.field.tokenIndex", "crate",
       "crate fields must reference valid token indices"},
      {"crate.fieldset.fieldIndex", "crate",
       "crate fieldsets must reference valid field indices"},
      {"crate.fieldset.terminator", "crate",
       "crate fieldsets must be sentinel-terminated"},
      {"crate.spec.fieldsetIndex", "crate",
       "crate specs must reference valid fieldset indices"},
      {"crate.spec.pathIndex", "crate",
       "crate specs must reference valid path indices"},
      {"crate.structure", "crate",
       "the crate container must decode without structural errors"},
      {"geom.camera.optics", "geom",
       "camera optical parameters must be positive and finite"},
      {"geom.camera.range", "geom",
       "camera clippingRange must be an increasing positive pair"},
      {"geom.camera.shutter", "geom",
       "camera shutter:open must not exceed shutter:close"},
      {"geom.camera.tokens", "geom",
       "camera projection/stereoRole must be valid tokens"},
      {"geom.curves.tokens", "geom",
       "curve type/basis/wrap must be valid tokens"},
      {"geom.curves.topology", "geom",
       "curveVertexCounts must match point counts and basis constraints"},
      {"geom.curves.widths", "geom",
       "curve widths must match the topology's expected count"},
      {"geom.encapsulation.nestedGprim", "geom",
       "Gprims must not be nested under other Gprims"},
      {"geom.gprim.arraySize", "geom",
       "Gprim array attributes must have consistent lengths"},
      {"geom.gprim.extent", "geom",
       "extent must be a [min, max] pair of finite vectors"},
      {"geom.gprim.orientation", "geom",
       "orientation must be leftHanded or rightHanded"},
      {"geom.gprim.purpose", "geom",
       "purpose must be default, render, proxy, or guide"},
      {"geom.gprim.visibility", "geom",
       "visibility must be inherited or invisible"},
      {"geom.mesh.topology.count", "geom",
       "faceVertexCounts entries must be at least 3"},
      {"geom.mesh.topology.index", "geom",
       "faceVertexIndices must be in range for the points array"},
      {"geom.mesh.topology.size", "geom",
       "faceVertexIndices length must equal the sum of faceVertexCounts"},
      {"geom.pointInstancer.arraySize", "geom",
       "PointInstancer per-instance arrays must have matching lengths"},
      {"geom.pointInstancer.indices", "geom",
       "protoIndices must be in range for the prototypes relationship"},
      {"geom.pointInstancer.prototypes", "geom",
       "the prototypes relationship must target existing prims"},
      {"geom.points.size", "geom",
       "Points positions/widths/ids arrays must have matching lengths"},
      {"geom.points.widths", "geom",
       "Points widths must be non-negative"},
      {"geom.primitive.axis", "geom",
       "primitive axis must be X, Y, or Z"},
      {"geom.primitive.size", "geom",
       "primitive radius/height/size must be positive and finite"},
      {"geom.primvar.indices", "geom",
       "primvar :indices must be in range for the value array"},
      {"geom.primvar.metadata", "geom",
       "primvars must carry valid interpolation/elementSize metadata"},
      {"geom.skel.animation.blendShapes", "geom",
       "SkelAnimation blendShapes and blendShapeWeights must match"},
      {"geom.skel.animation.joints", "geom",
       "SkelAnimation joints and per-joint arrays must match"},
      {"geom.skel.animation.transforms", "geom",
       "SkelAnimation transforms must match the joint count"},
      {"geom.skel.binding.animationSource", "geom",
       "skel:animationSource must target a SkelAnimation prim"},
      {"geom.skel.binding.api", "geom",
       "UsdSkelBinding properties require SkelBindingAPI to be applied"},
      {"geom.skel.binding.root", "geom",
       "SkelBindingAPI must be applied on a SkelRoot or beneath one"},
      {"geom.skel.binding.skeleton", "geom",
       "skel:skeleton must target a Skeleton prim"},
      {"geom.skel.blendShape.inbetween", "geom",
       "inbetween shapes must match the blend shape's offset count"},
      {"geom.skel.blendShape.normalOffsets", "geom",
       "normalOffsets must match the offsets count"},
      {"geom.skel.blendShape.offsets", "geom",
       "BlendShape offsets must be finite vectors"},
      {"geom.skel.blendShape.pointIndices", "geom",
       "pointIndices must match the offsets count and be non-negative"},
      {"geom.skel.skeleton.jointNames", "geom",
       "jointNames must match the joints count"},
      {"geom.skel.skeleton.joints", "geom",
       "Skeleton should author uniform token[] joints"},
      {"geom.skel.skeleton.topology", "geom",
       "Skeleton joint paths must form a valid topology"},
      {"geom.skel.skeleton.transforms", "geom",
       "bind/rest transforms must match the joint count"},
      {"geom.skel.skinning.elementSize", "geom",
       "jointIndices/jointWeights elementSize must agree"},
      {"geom.skel.skinning.index", "geom",
       "jointIndices must be in range for the bound skeleton's joints"},
      {"geom.skel.skinning.interpolation", "geom",
       "skinning primvars must author constant or vertex interpolation"},
      {"geom.skel.skinning.pair", "geom",
       "jointIndices and jointWeights must be authored together"},
      {"geom.skel.skinning.size", "geom",
       "skinning primvar lengths must match the point count times elementSize"},
      {"geom.skel.skinning.weight", "geom",
       "jointWeights must be non-negative and normalized per point"},
      {"geom.stage.metersPerUnit", "geom",
       "the root stage should declare metersPerUnit (usdchecker StageMetadataChecker)"},
      {"geom.stage.upAxis", "geom",
       "the root stage should declare an upAxis (usdchecker StageMetadataChecker)"},
      {"geom.subset.familyType", "geom",
       "materialBind-family subsets must use a restricted familyType"},
      {"geom.subset.indices", "geom",
       "GeomSubset indices must be in range for the parent topology"},
      {"geom.subset.parent", "geom",
       "a GeomSubset must be a direct child of an Imageable prim"},
      {"vol.fieldAsset.dataType", "geom",
       "field asset dataType must be a valid token"},
      {"vol.fieldAsset.fieldClass", "geom",
       "field asset fieldClass must be a valid token"},
      {"vol.fieldAsset.filePath", "geom",
       "field asset filePath must be a non-empty asset path"},
      {"vol.fieldAsset.vectorDataRoleHint", "geom",
       "vectorDataRoleHint must be a valid token"},
      {"vol.volume.fieldRel", "geom",
       "Volume field relationships must target field asset prims"},
      {"lux.dome.poleAxis", "lux",
       "dome light poleAxis must be scene, Y, or Z"},
      {"lux.light.angle", "lux",
       "distant light angle must be within valid range"},
      {"lux.light.inputs", "lux",
       "light inputs must be finite and non-negative where required"},
      {"lux.light.size", "lux",
       "light geometric inputs (radius, width, ...) must be positive"},
      {"lux.relationship.target", "lux",
       "light relationships (filters, portals) must target existing prims"},
      {"lux.shadow.inputs", "lux",
       "ShadowAPI inputs must be finite and valid"},
      {"lux.shaping.inputs", "lux",
       "ShapingAPI inputs must be finite and within range"},
      {"lux.texture.file", "lux",
       "light texture file must be a non-empty asset path"},
      {"lux.texture.format", "lux",
       "dome/rect light texture format must be a supported image type"},
      {"package.centralDirectory.bounds", "package",
       "the ZIP central directory must be contiguous and in bounds"},
      {"package.centralDirectory.comment", "package",
       "USDZ archives must have an empty ZIP comment"},
      {"package.centralDirectory.entryCount", "package",
       "central-directory entry count must match local headers"},
      {"package.centralDirectory.mismatch", "package",
       "central-directory metadata must match the local headers"},
      {"package.centralDirectory.missing", "package",
       "the ZIP end-of-central-directory record must exist"},
      {"package.centralDirectory.multidisk", "package",
       "multi-disk ZIP archives are not valid USDZ packages"},
      {"package.centralDirectory.structure", "package",
       "central-directory entry headers must be well-formed"},
      {"package.centralDirectory.trailingData", "package",
       "the archive must not carry trailing data after the EOCD"},
      {"package.dependency.external", "package",
       "authored dependencies must be package-relative"},
      {"package.dependency.missing", "package",
       "authored dependencies must be present in the package"},
      {"package.entry.alignment", "package",
       "USDZ entry data must begin on a 64-byte boundary"},
      {"package.entry.compression", "package",
       "USDZ entries must use ZIP store mode (no compression)"},
      {"package.entry.crc", "package",
       "entry payloads must match their local-header CRC-32"},
      {"package.entry.dataDescriptor", "package",
       "USDZ entries must carry sizes in the local-file header"},
      {"package.entry.duplicate", "package",
       "package entry names must be unique"},
      {"package.entry.encryption", "package",
       "USDZ entries must not be encrypted"},
      {"package.entry.extension", "package",
       "entry types should be within the portable USDZ extension set"},
      {"package.entry.path", "package",
       "package entry names must be safe relative paths"},
      {"package.entry.size", "package",
       "stored entries must have equal compressed/uncompressed sizes"},
      {"package.root.first", "package",
       "the first USDZ entry must be the package root USD layer"},
      {"package.structure.bounds", "package",
       "ZIP entry payloads must be within the archive bounds"},
      {"package.structure.empty", "package",
       "a USDZ archive must contain at least one entry"},
      {"package.structure.header", "package",
       "ZIP local-file headers must be well-formed"},
      {"physics.articulation.nested", "physics",
       "ArticulationRootAPI must not be nested under another articulation"},
      {"physics.articulation.staticBody", "physics",
       "an articulation root must not be a static (kinematic-less) body"},
      {"physics.collider.points", "physics",
       "collision meshes must have valid point data"},
      {"physics.collision.approximation", "physics",
       "collision approximation must be a valid token"},
      {"physics.collisionGroup.filteredGroups", "physics",
       "filteredGroups must target CollisionGroup prims"},
      {"physics.collisionGroup.mergeGroup", "physics",
       "mergeGroupName must be consistent across merged groups"},
      {"physics.drive.dof", "physics",
       "a drive's degree of freedom must match its joint type"},
      {"physics.drive.type", "physics",
       "drive type must be force or acceleration"},
      {"physics.drive.value", "physics",
       "drive gains and targets must be finite"},
      {"physics.extension.mjc.array", "physics",
       "MJC extension arrays must have valid lengths"},
      {"physics.extension.mjc.range", "physics",
       "MJC extension values must be within range"},
      {"physics.extension.mjc.relationship", "physics",
       "MJC extension relationships must target valid prims"},
      {"physics.extension.mjc.token", "physics",
       "MJC extension tokens must be valid"},
      {"physics.extension.newton.asset", "physics",
       "Newton extension asset paths must be non-empty"},
      {"physics.extension.newton.lookup", "physics",
       "Newton extension lookups must reference existing entries"},
      {"physics.extension.newton.range", "physics",
       "Newton extension values must be within range"},
      {"physics.extension.newton.relationship", "physics",
       "Newton extension relationships must target valid prims"},
      {"physics.extension.newton.token", "physics",
       "Newton extension tokens must be valid"},
      {"physics.inertia", "physics",
       "mass/density/inertia values must be physically meaningful"},
      {"physics.joint.axis", "physics",
       "joint axis must be X, Y, or Z"},
      {"physics.joint.body", "physics",
       "joint body0/body1 must target Xformable prims"},
      {"physics.joint.distance", "physics",
       "distance joint min must not exceed max"},
      {"physics.joint.limit", "physics",
       "joint limits must be within the joint type's valid range"},
      {"physics.joint.transform", "physics",
       "joint local positions/rotations must be finite"},
      {"physics.limit.dof", "physics",
       "a limit's degree of freedom must match its joint type"},
      {"physics.limit.range", "physics",
       "limit low must not exceed high"},
      {"physics.motion", "physics",
       "MotionAPI values must be finite and valid"},
      {"physics.preliminary.acceleration", "physics",
       "preliminary gravitationalForce acceleration must be finite"},
      {"physics.preliminary.normal", "physics",
       "preliminary infinite-plane normal must be a unit-lengthable vector"},
      {"physics.preliminary.range", "physics",
       "preliminary physics values must be within range"},
      {"physics.preliminary.relationship", "physics",
       "preliminary physics relationships must target valid prims"},
      {"physics.quaternion", "physics",
       "physics quaternions must be finite and non-zero"},
      {"physics.relationship.target", "physics",
       "physics relationships must target existing prims"},
      {"physics.rigidBody.xformable", "physics",
       "RigidBodyAPI must be applied to an Xformable prim"},
      {"physics.scene.gravity", "physics",
       "gravityDirection must be normalizable and magnitude finite"},
      {"physics.schemaPlacement", "physics",
       "physics API schemas must be applied to valid prim types"},
      {"physics.value.range", "physics",
       "physics scalar values must be within their valid ranges"},
      {"render.product.aspectRatioConformPolicy", "render",
       "RenderProduct aspectRatioConformPolicy must be a valid token"},
      {"render.product.relationship", "render",
       "RenderProduct orderedVars/camera must target valid prims"},
      {"render.settings.aspectRatioConformPolicy", "render",
       "RenderSettings aspectRatioConformPolicy must be a valid token"},
      {"render.settings.relationship", "render",
       "RenderSettings products/camera must target valid prims"},
      {"render.var.sourceType", "render",
       "RenderVar sourceType must be a valid token"},
      {"shade.connection.target", "shade",
       "shader connections must target existing attributes of connectable prims"},
      {"shade.encapsulation.imageableInMaterial", "shade",
       "only connectable prims belong under a Material (usdchecker EncapsulationMaterialValidator)"},
      {"shade.encapsulation.shaderParent", "shade",
       "Shaders must be parented by a Material or NodeGraph"},
      {"shade.material.binding", "shade",
       "material:binding properties must be relationships"},
      {"shade.material.bindingAPI", "shade",
       "material bindings require MaterialBindingAPI to be applied"},
      {"shade.material.outputConnection", "shade",
       "Material terminal outputs must connect to a shader output"},
      {"shade.materialX.configAPI", "shade",
       "MaterialX layers require MaterialXConfigAPI with version metadata"},
      {"shade.materialX.nodeReference", "shade",
       "MaterialX node references must resolve to defined nodes"},
      {"shade.materialX.output", "shade",
       "MaterialX shaders must author their declared outputs"},
      {"shade.materialX.referencePrimPath", "shade",
       "MaterialX references must use valid prim paths"},
      {"shade.materialX.sourceUri", "shade",
       "MaterialX source URIs must be non-empty asset paths"},
      {"shade.materialX.version", "shade",
       "MaterialX version metadata must be a valid version string"},
      {"shade.normalMap.scaleBias", "shade",
       "8-bit normal maps must remap [0,1] to [-1,1] and stay raw (usdchecker NormalMapTextureValidator)"},
      {"shade.preview.inputRange", "shade",
       "UsdPreviewSurface scalar inputs must be within [0,1] where specified"},
      {"shade.preview.inputType", "shade",
       "UsdPreviewSurface inputs must match the registry value types"},
      {"shade.preview.opacityMode", "shade",
       "opacityThreshold/opacityMode combinations must be consistent"},
      {"shade.preview.unknownInput", "shade",
       "inputs:* on UsdPreviewSurface must be registry inputs"},
      {"shade.primvarReader.result", "shade",
       "UsdPrimvarReader outputs:result must match the reader's type"},
      {"shade.primvarReader.varname", "shade",
       "UsdPrimvarReader must author a non-empty inputs:varname"},
      {"shade.shader.id", "shade",
       "id-source shaders must name a registry shader id (usdchecker ShaderSdrCompliance)"},
      {"shade.shader.typeMismatch", "shade",
       "shader input declared types must match the registry exactly (usdchecker MismatchedPropertyType)"},
      {"shade.subset.materialBindFamily", "shade",
       "material-bound GeomSubsets must be in the materialBind family (usdchecker SubsetMaterialBindFamilyName)"},
      {"shade.uvTexture.file", "shade",
       "UsdUVTexture must author a non-empty inputs:file"},
      {"shade.uvTexture.sourceColorSpace", "shade",
       "sourceColorSpace must be auto, raw, or sRGB"},
      {"shade.uvTexture.wrap", "shade",
       "wrapS/wrapT must be valid wrap tokens"},
  };
  if (count) *count = sizeof(kRules) / sizeof(kRules[0]);
  return kRules;
}

void ApplyUsdcheckerCompatSeverities(USDValidationResult *result) {
  if (!result) {
    return;
  }
  // Rules OpenUSD's usdchecker reports as ERRORS where the lightusd defaults
  // use warnings (or where the presence rules default to warnings). Keyed by
  // rule id so the upgrade also covers issues merged in from the
  // byte-container checks.
  static constexpr const char* kErrorRules[] = {
      "geom.stage.upAxis",
      "geom.stage.metersPerUnit",
      "core.layer.defaultPrim.missing",
      "core.dependency.unresolvable",
      "core.schema.attributeType",
      "geom.encapsulation.nestedGprim",
      "geom.subset.parent",
      "geom.subset.familyType",
      "shade.material.bindingAPI",
      "shade.encapsulation.shaderParent",
      "shade.encapsulation.imageableInMaterial",
      "shade.preview.inputType",
      "shade.shader.typeMismatch",
      "shade.shader.id",
      "shade.subset.materialBindFamily",
      "shade.normalMap.scaleBias",
  };
  for (USDValidationIssue &issue : result->issues) {
    if (issue.severity != USDValidationSeverity::Warning) continue;
    for (const char* id : kErrorRules) {
      if (issue.rule_id == id) {
        issue.severity = USDValidationSeverity::Error;
        break;
      }
    }
  }
}

std::string FormatValidationResult(const USDValidationResult &result) {
  std::ostringstream ss;
  ss << "AOUSD validation report (" << GetAOUSDCoreSpecVersionString()
     << ")\n";
  ss << "Checked rule groups: " << result.checked_groups.group_summary()
     << "\n";

  const std::vector<const USDValidationIssue *> ordered =
      GetOrderedValidationIssues(result);

  if (!ordered.empty()) {
    ss << "\n";
    for (const USDValidationIssue *issue : ordered) {
      ss << (issue->severity == USDValidationSeverity::Error ? "ERROR"
                                                             : "WARN ")
         << " [" << issue->rule_id << "] ";
      if (!issue->location.empty()) {
        ss << issue->location << ": ";
      }
      ss << issue->message << "\n";
    }
  }

  const size_t errors = result.error_count();
  const size_t warnings = result.warning_count();

  ss << "\nResult: ";
  if (errors > 0) {
    ss << "FAILED - " << Pluralize(errors, "error") << ", "
       << Pluralize(warnings, "warning") << "\n";
  } else if (warnings > 0) {
    ss << "PASSED with warnings - " << Pluralize(warnings, "warning") << "\n";
  } else {
    ss << "PASSED - no issues found\n";
  }

  return ss.str();
}

std::string ValidationOptions::group_summary() const {
  std::string s;
  const auto add = [&](bool enabled, const char *name) {
    if (!enabled) {
      return;
    }
    if (!s.empty()) {
      s += ", ";
    }
    s += name;
  };
  add(core, "core");
  add(geom, "geom");
  add(shade, "shade");
  add(lux, "lux");
  add(physics, "physics");
  add(package, "package");
  add(crate, "crate");
  add(arkit, "arkit");
  if (s.empty()) {
    s = "(none)";
  }
  return s;
}

}  // namespace next
}  // namespace lightusd
