#!/usr/bin/env python3
"""Compile schema/shader JSON manifests into dependency-free checker tables."""
import argparse
import json
import re
from pathlib import Path


def generate(schema, shader):
    q = lambda value: json.dumps(value, ensure_ascii=True)
    lines = ['// SPDX-License-Identifier: Apache-2.0',
             '// Generated by scripts/generate-checker-definitions.py; do not edit.',
             '// Schema provenance: ' + json.dumps(schema.get('openusd', {}), sort_keys=True)]
    for s in schema['schemas']:
        lines.append('schema(%s);' % ', '.join(q(s.get(k, '')) for k in
                     ('name', 'inherits', 'kind', 'propertyNamespacePrefix', 'source')))
        for p in s['properties']:
            lines.append('property(%s, %s, %s, %s, {%s});' % (
                q(p['name']), q(p['type']), str(p['kind'] == 'relationship').lower(),
                q(p.get('variability', '')), ', '.join(map(q, p.get('allowedTokens', [])))))
    for s in shader['shaders']:
        lines.append('shader(%s, %s, %s, {%s}, {%s});' % (
            q(s['identifier']), q(s.get('sourceType', '')), q(s.get('source', '')),
            ', '.join('{%s, %s}' % (q(k), q(v)) for k, v in sorted(s['inputs'].items())),
            ', '.join('{%s, %s}' % (q(k), q(v)) for k, v in sorted(s.get('outputs', {}).items()))))
    return '\n'.join(lines) + '\n'


def main():
    root = Path(__file__).resolve().parents[1]
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--schemas', type=Path, default=root/'doc/generated/openusd-schema-26.08.json')
    p.add_argument('--shaders', type=Path, default=root/'tools/lusdchecker/definitions/shaders.json')
    p.add_argument('--output', type=Path, default=root/'src/next/validation/generated-definitions.inc')
    p.add_argument('--check', action='store_true')
    a = p.parse_args()
    data = generate(json.loads(a.schemas.read_text()), json.loads(a.shaders.read_text()))
    references = json.loads((root/'tools/lusdchecker/reference-errors.json').read_text())
    rule_table = (root/'src/next/validation/usd-validation-report.cc').read_text()
    registered = set(re.findall(r'\{"([^" ]+)", "[a-z]+"', rule_table))
    mapped = {rule for entry in references['errors'].values() for rule in entry['rules']}
    if mapped - registered:
        p.error('reference mapping contains unregistered rules: ' + ', '.join(sorted(mapped - registered)))
    reverse = {}
    for error, entry in references['errors'].items():
        for rule in entry['rules']:
            reverse.setdefault(rule, []).append(error)
    metadata = '// Generated by scripts/generate-checker-definitions.py; do not edit.\n'
    for rule, errors in sorted(reverse.items()):
        metadata += '{%s, {%s}},\n' % (json.dumps(rule), ', '.join(map(json.dumps, sorted(errors))))
    metadata_path = root/'src/next/validation/generated-reference-errors.inc'
    if a.check and (not metadata_path.exists() or metadata_path.read_text() != metadata):
        p.error('checker reference metadata is stale; run the generator')
    if not a.check:
        metadata_path.write_text(metadata)
    if a.check:
        if not a.output.exists() or a.output.read_text() != data:
            p.error('checker definitions are stale; run the generator')
    else:
        a.output.write_text(data)


if __name__ == '__main__':
    main()
